### PR TITLE
don't hard error on invalid options

### LINKED ISSUE #8: issue with formatter and indentation rule
When turning on the indentation rule, I'm getting

```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
TypeError: Cannot read property 'length' of undefined
    at dotindex (/Users/kelly.selden/Sites/dustbunny/node_modules/text-table/index.js:59:31)
    at /Users/kelly.selden/Sites/dustbunny/node_modules/text-table/index.js:11:21
    at Array.forEach (native)
    at forEach (/Users/kelly.selden/Sites/dustbunny/node_modules/text-table/index.js:73:31)
    at /Users/kelly.selden/Sites/dustbunny/node_modules/text-table/index.js:10:9
    at Array.reduce (native)
    at reduce (/Users/kelly.selden/Sites/dustbunny/node_modules/text-table/index.js:63:30)
    at module.exports (/Users/kelly.selden/Sites/dustbunny/node_modules/text-table/index.js:9:20)
    at prettyTable (/Users/kelly.selden/Sites/dustbunny/node_modules/ember-css-modules-reporter/lib/formatter.js:58:10)
    at formatMessages (/Users/kelly.selden/Sites/dustbunny/node_modules/ember-css-modules-reporter/lib/formatter.js:20:15)
```

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #8

### CODE REVIEW

File: lib/formatter.js [hunk 1]
```diff
@@ -28,10 +28,18 @@ module.exports = function formatMessages(results) {
         messageType = chalk.yellow(messageType);
       }
 
+      let line, column;
+      if (message.stylelintType === 'invalidOption') {
```
Comment (dfreeman) [inline lib/formatter.js]: I've been trying to avoid baking any specific knowledge of stylelint here if possible. Could we just default to `''` if `message.{line,column}` are non-numeric?

Comment (kellyselden) [reply lib/formatter.js]: yep

**Comment by kellyselden** [comment]
updated to be more agnostic with a comment.

**Comment by dfreeman** [comment]
👍 Thanks!
